# Generated by Django 4.2.23 on 2025-12-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('國中', '國中'), ('國小', '國小')], max_length=10)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
    ]
