# Generated by Django 4.2.23 on 2026-01-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswerrecord',
            name='selected_option_id',
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.examoption'),
        ),
    ]
