# Generated by Django 4.2.23 on 2025-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='convener',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
