# Generated by Django 4.2.23 on 2025-12-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_league_convener'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('國中', '國中'), ('國小', '國小')], max_length=10)),
                ('grade', models.IntegerField()),
                ('classroom', models.CharField(max_length=20)),
                ('teachers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', '老師'), ('school_admin', '學校管理員'), ('union_leader', '聯盟召集人'), ('global_leader', '總召集人'), ('student', '學生')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('first_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=10)),
                ('teacher_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.useraccount')),
            ],
        ),
    ]
