# Generated by Django 4.2.23 on 2026-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_examanswerrecord_selected_option_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('category', models.CharField(max_length=50, verbose_name='類別')),
                ('content', models.TextField(verbose_name='內容')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
