# Generated by Django 4.2.23 on 2025-12-16 03:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_class_useraccount_teacher_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('island', models.CharField(max_length=50)),
                ('correct_ratio', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
