# Generated by Django 4.2.23 on 2026-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
