# Generated by Django 4.2.23 on 2025-12-18 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_competitionscore_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=50)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_key', models.CharField(choices=[('EngToChi', '英翻中'), ('ChiToEng', '中翻英'), ('Listening', '聽力')], max_length=20)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='students.exampaper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('question_type', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('island', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('exam_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.exampart')),
            ],
        ),
        migrations.CreateModel(
            name='ExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='students.examquestion')),
            ],
        ),
    ]
