# Generated by Django 4.2.23 on 2025-12-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_exampaper_exampart_examrecord_examquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_id', models.IntegerField(blank=True, null=True)),
                ('selected_text', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.examrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.examquestion')),
            ],
        ),
    ]
