# Generated by Django 4.2.20 on 2025-12-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('zh_to_en', '中翻英'), ('en_to_zh', '英翻中'), ('cloze', '克漏字'), ('letter', '字母題型')], max_length=20)),
                ('question_text', models.TextField()),
                ('correct_option_id', models.IntegerField()),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptionZH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
