# Generated by Django 4.2.23 on 2025-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('zh_to_en', '中翻英'), ('en_to_zh', '英翻中'), ('cloze', '克漏字'), ('letter', '字母')], max_length=20),
        ),
    ]
