"""
Django settings for Englishability project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from corsheaders.defaults import default_headers

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-02d6l&@pizp8aq$d%s5p*hu6+wol@vx8o34b!=6m00u6y8t9ks'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#     'localhost', 
#     '127.0.0.1', 
#     '192.168.3.50',  # 访问的宿主机 IP
#     '192.168.3.51'
# ]

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "ngrok-skip-browser-warning",  # ⭐ 關鍵
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'questionbank',
    'students',
    'rest_framework_simplejwt',
    'corsheaders',
    'mozilla_django_oidc'
]
AUTH_USER_MODEL = 'students.UserAccount'    
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ⭐ 一定要最前面之一
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Englishability.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "請輸入 JWT Token：Bearer <your_token>"
        }
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),  # Access Token 30 分鐘
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),     # Refresh Token 7 天
    "ROTATE_REFRESH_TOKENS": True,                  # 刷新 refresh token
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),               # Authorization: Bearer <token>
}

WSGI_APPLICATION = 'Englishability.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # 你自訂的 template 可放這
        'APP_DIRS': True,  # ⚠️ 必須 True 才能載入 drf_yasg 的 template
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # ⚠️ 必須有 request
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'englishability_db'),
        'USER': os.getenv('POSTGRES_USER', 'englishability_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'englishability_pass'),
        'HOST': os.getenv('POSTGRES_HOST', 'english-db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST','english-redis')}:{os.getenv('REDIS_PORT','6379')}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
DEFAULT_TO_EMAIL = os.getenv("DEFAULT_TO_EMAIL")

FRONTEND_URL = " https://4ef4c372f5d7.ngrok-free.app"

# =========================
# OIDC 設定 
# =========================
OIDC_RP_CLIENT_ID = "kh_vendor_a95da8c087d6f9c3f62acc5e22c26f42"

OIDC_RP_CLIENT_SECRET = "38efe712ebe3b6af5d7365441cf2e4d5b6d3c9dc07aa977f74d8f1c8e6c134d1"

OIDC_OP_DISCOVERY_ENDPOINT = "https://oidc.kh.edu.tw/.well-known/openid-configuration"

OIDC_RP_SIGN_ALGO = "RS256"

OIDC_RP_SCOPES = "openid email kh_profile kh_classes kh_titles"

OIDC_RP_CALLBACK_URL = "https://englishability.rootadviser.com/api/oidccallback/"

# =========================
# Token endpoints 
# =========================

OIDC_OP_AUTHORIZATION_ENDPOINT = "https://oidc.kh.edu.tw/oauth2/auth"

OIDC_OP_TOKEN_ENDPOINT = "https://oidc.kh.edu.tw/oauth2/token"

OIDC_OP_JWKS_ENDPOINT = "https://oidc.kh.edu.tw/.well-known/jwks.json"

# =========================
# User info 
# =========================

OIDC_OP_USER_ENDPOINT = "https://oidc.kh.edu.tw/userinfo"

# =========================
# OIDC 
# =========================

OIDC_RP_SIGN_ALGO = "RS256"

OIDC_CREATE_USER = True

OIDC_USERNAME_ALGO = "accounts.authentication.username_algo"

OIDC_DJANGO_USER_MODEL = "auth.User"

# =========================
# Django login 設定 
# =========================

LOGIN_REDIRECT_URL = "/api/me/"
LOGOUT_REDIRECT_URL = "/"